### ISSUE TITLE
CIP: EventStream

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/CIP#117]
```
cip: 117
title: EventStream
author: Joel Thorstensson (@oed)
discussions-to: https://github.com/ceramicnetwork/CIP/issues/117
status: Draft
category: Standards
type: RFC
created: 2022-04-22
requires: Streamtypes (CIP-5)
```

## Simple Summary

This CIP describes the Tile document which is a very general stream type that represents and event stream, where events are emitted by a  [DID](https://w3c.github.io/did-core/).

## Abstract

The EventStream allows DIDs to create a stream of events that are ordered. This stream type doesn't have the notion of a state object in the same way that a TileDocument does. Instead it keeps track of events that have been emitted and it's up to the application how to interpret these events. For example, an indexing service could be built on top of one or multiple *EventStreams* to create a collection of items created by one or multiple users.

## Motivation

While the TileDocument stream type is useful to represent a JSON object, many applications require collections of objects from one or multiple users. Certain applications might also want to interpret events in different ways and provide various different way to query the data. The EventStream is agnostic as to how events that are emitted should be interpreted and instead an application developer can choose to implement a CRDT, a database, or a searchable index on top of one or multiple event streams. This will enable much greater data composability and scalability of the Ceramic network because processing is unbundled from the event stream itself.

## Specification

Below the commit formats and state transitions of the EventStream are specified. Together they should inform an implementer with the general idea needed to implement this stream type in Ceramic.

### Commit formats

The **Genesis commit** has the following required properties:

* `owners` - the owners array in the header needs to contain only DID strings

In addition to the required properties above the genesis commit may inlcude `schema`, `tags`, and `unique`. The `unique` property should include randomness as a string to ensure that there is no other document that is exactly the same.

The genesis commit must be stored using *dag-cbor*. 

**Signed commits** of a Tile document are encoded using [dag-jose](https://github.com/ceramicnetwork/js-dag-jose). Other than that they conform to the standard commit format. The content of the `data` property should contain the event data. If the `schema` is defined in the genesis commit, the contents of the data property must conform to this json-schema.

### State transitions

Below the state transition logic for the three different supported commits is described.

#### Applying the Genesis event

When the genesis event is applied a `StreamState` object is created that looks like this:

```js
{
  doctype: 'event-stream',
  metadata: {
    owners: genesisCommit.owners,
    schema: genesisCommit.schema,
    family: genesisCommit.family,
    tags: genesisCommit.tags,
    unique: genesisCommit.unique
  },
  content: null,
  signature: SignatureStatus.GENESIS,
  anchorStatus: AnchorStatus.NOT_REQUESTED,
  log: [new CID(genesisCommit)]
}
```

In addition to this, the following should be verified:

* `genesisCommit.data` MUST equal `null`
* `owners` is an array containing only one DID
* If `schema` is defined it should be Ceramic CommitId string
* If `tags` is defined it should be an array of strings

#### Applying a Signed Commit

When a signed commit is applied the `StreamState` object should be modified in the following way:

```js
state.next.content = signedCommit.data,
state.signature = SignatureStatus.SIGNED
state.anchorStatus = AnchorStatus.NOT_REQUESTED
state.log.push(new CID(signedCommit))
```

* If `schema` is defined the data in the `singedCommit.data` should be valid according to the schema
* The **dag-jose** signature should be valid and signed by the DID in the `controllers` array in the `metadata` property
* The **dag-jose** signature should include a `kid` property in it's header which specifies the `keyFragment` as well as the `version-id` of the public key that was used to sign the commit

#### Applying an Anchor Commit

When an anchor commit is applied the `StreamState` object should be modified in the following way:

```js
state.content = state.next.content
delete state.next
state.anchorStatus = AnchorStatus.ANCHORED
state.anchorProof = anchorCommit.proof
state.log.push(new CID(anchorCommit))
```

No additional validation needs to happen at this point in the state transition function.

## Rationale

The EventStream specification provides a slight modification to the TileDocument stream type to create an event stream in Ceramic. By allowing a schema to be defined, the events of the document can be constrained. This gives developers both flexibility and control. The `content` just represents the latest the EventStream. Implementers should also provide an api to fetch previous event data based on the event log in the StreamState.

## Implementation

No implementation exists currently

## Security Considerations

See TileDocument (CIP-8).

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by qbig** [comment]
Will this become the core abstraction underneath all streams type or just one of the stream type?

**Comment by oed** [comment]
Closing this CIP as there is no longer any plan to implement this as described here.

**Comment by oed** [comment]
For context @qbig there is a plan to create an abstracted event stream in the Rust implementation of Ceramic. More info to come about this in the future.

**Comment by qbig** [comment]
Is this currently being inherited by #124 as the concept of an "Event" is not mentioned in other CIPs ? https://github.com/ceramicnetwork/CIP/pull/124

**Comment by oed** [comment]
CIP #124 is a protocol for exchanging events. The idea is that the core protocol stops caring about stream types and only validates the integrity of the event log itself. 
Currently the full core protocol is specified here:
https://developers.ceramic.network/protocol/
