### ISSUE TITLE
Profiles Index

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#12]
```
cip: 13
title: Profiles Index
author: Michael Sena (@michaelsena), Joel Thorstensson (@oed)
status: Draft
category: Standards
type: RFC
created: 2020-05-22
requires: Tile Doctype (CIP-8), String Map (CIP-9)
```

## Simple Summary

**Profiles Index** is a document that stores an index of a DID's profiles.

## Abstract

For DIDs to be usable in the context of consumer applications they often need to support public metadata such as profiles. Over time users (or applications) may desire to create multiple profiles (i.e. personas). Examples of this might include a basic profile, work profile, education profile, gaming profile, etc. Without a standardized way for DID's to associate multiple profiles to their identity, there would be no single index for apps to query when resolving these various profiles, and users would be forced to use only one profile everywhere. 

Profiles Index is an extensible directory that stores links to a DID's profiles. It does not store profile data, but rather stores links to profile data. By standardizing how one or more profiles are associated to a DID, Profiles Index simplifies the process of managing multiple profiles for an identity and enables applications to have a common interface for discovering and interacting with those various profiles.

Profiles Index is a subdirectory in the [Identity Index (IDX) (CIP-11)](https://github.com/ceramicnetwork/CIP/issues/3) and is often linked from the [Root Index (CIP-12)](https://github.com/ceramicnetwork/CIP/issues/21).

## Motivation

**A Core Piece of Identity**: Profiles are often most associated with identity, and the Profiles Index allows DIDs to build an index of one or more profiles.

**Future-proof & Extensibility of Multiple Profiles**: Even if DID's only desire to support one basic profile in the beginning, using the Profiles Index allows for future extensibility. Adding new profiles just requires adding them to the index.

**Standardization & Interoperability**: By defining a common interface for creating an index of profiles, Profiles Index enables any application to discover and interact with the profile of their choice.

## Specification

The Profiles Index specification includes a doctype, schema, table, and tag.

![Profiles Index Diagram](https://uploads-ssl.webflow.com/5e4b58d7f08158ece0209bbd/5f03b89cf732ddd7403dca98_Profiles%20Index.png)

### Doctype

Profiles Index is a [Tile Doctype (CIP-8)](https://github.com/ceramicnetwork/CIP/issues/56).

### Schema

Profiles Index utilizes the [String Map (CIP-9)](https://github.com/ceramicnetwork/CIP/issues/50) schema, which simply stores a list of strings which map to other strings. In this context the key string is used to name the profile, while the value string is used to store the location of the profile. A reference to this schema should be included in your Profiles Index document when it is created.

### Table

The [Profiles Index Table](https://github.com/ceramicnetwork/CIP/blob/cip/prd/CIPs/CIP-PRD/tables/profiles-index-table.csv) contains the standard set of properties that may be contained in any given Profiles Index. New properties can be added to the table by following the steps below. Additional properties not found in this table may be stored in any Profiles Index, however they may be less interoperable since others may not know what they represent. Here are some common examples of properties stored in the Profiles Index:

- `basic`: a link to a [Basic Profile (CIP-19)](https://github.com/ceramicnetwork/CIP/issues/32), which contains general profile information for a DID
- `work`: a link to a Work Profile, which contains work-related profile information for a DID
- `education`: a link to an Education Profile, which contains education-related profile information for a DID
- `gaming`: a link to a Gaming Profile, which contains gaming-related profile information for a DID

**How to add a new property to the Profiles Index Table**

1. Choose a unique, descriptive property name.
2. Add a description for your property.
3. Submit a PR to the CIP repository updating the [Profiles Index Table](https://github.com/ceramicnetwork/CIP/blob/cip/prd/CIPs/CIP-PRD/tables/profiles-index-table.csv) with your property.
4. Mention the authors of this CIP in the comments of your PR.

### Tags

When creating a Profiles Index document, add `ProfilesIndex` to the **tags** field.

## Example

An example Profiles Index document.

```json
"doctype": "tile"
"schema": "<insert canonical schema for String Map>"
"tags": ["ProfilesIndex", "StringMap"]
"content": {
  "basic": "ceramic://bafyljsdf1...",
  "work": "ceramic://bafysdfoijwe2...",
  "education": "ceramic://bafysdfoijwe3...",
  "gaming": "ceramic://bafysdfoijwe4..."
}
```

## Suggested Usage

**Root Index**: Profiles Index provides a directory of profiles, however profiles are just one type of resource that can be associated with a DID. The [Root Index (CIP-12)](https://github.com/ceramicnetwork/CIP/issues/21) provides a top-level root directory for resources, and can contain a property called `profiles` which stores a link to a Profiles Index document. The recommended configuration for mapping from a DID to the Profiles Index is: `DID`/`Root Index`/`Profiles Index`.

## Rationale

**Extensibility & Flexibility:** It is impossible to predict all of the types of profiles that need to be associated with any particular DID. Therefore Profiles Index was designed to be an infinitely extensible directory that can support any number of profiles.

**Decentralization & Trust:** Profile directory information is data that needs to be globally-available, censorship-resistant, and live permissionlessly in the public domain (not on any single server). Additionally this information should be owned by a DID and will need to be updated from time to time. These requirements make Ceramic the most appropriate platform for publishing this content.

## Implementation

**String Map Schema:** Find the String Map Schema [here](https://github.com/ceramicnetwork/CIP/issues/50).

**Profiles Index Table:** Find the table containing standard Profiles Index properties [here](https://github.com/ceramicnetwork/CIP/blob/cip/prd/CIPs/CIP-PRD/tables/profiles-index-table.csv).

**Libraries:** Not yet available.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by dazuck** [comment]
Might want to call out what a profile is _not_ -- aka it's not a verified identity or links to others -- this is self-attested info and as you say can have multiple profiles.

**Comment by dazuck** [comment]
Also may want to call out how we suggest/envision apps use this? Aka if a profile already exists, just use that. If they need custom, extend (rather than duplicate)

**Comment by oed** [comment]
Schema for this document that allows any property:
```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/ProfileRouter",
  "definitions": {
    "ProfileRouter": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "pattern": "^ceramic:\/\/.+"
      },
      "title": "ProfileRouter"
    }
  }
}
```

Looks like you have some formatting issues with "```json" btw.

**Comment by gvelez-postmates** [comment]
I think 'work' 'education' 'gaming' should be considered 'tags' and any tag be allowed?  Most of my stuff doesn't fit into any of those three categories...

**Comment by oed** [comment]
Stale, closing.
