### ISSUE TITLE
Keychains Index

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#13]
```
cip: 15
title: Keychains Index
author: Michael Sena (@michaelsena), Joel Thorstensson (@oed)
status: Draft
category: Standards
type: RFC
created: 2020-05-22
requires: Tile Doctype (CIP-8), String Map (CIP-9)
```

## Simple Summary

**Keychains Index** is a document that stores mappings to a DID's various keychains.

## Abstract

Decentralized identifiers (DIDs) have a set of keys (i.e. management, signing, encryption, etc) that are controlled by a seed. However, sometimes it is desirable to use other keys for authenticating or performing other actions. Examples of this might include using crypto keys from various technologies, networks, or wallets to authenticate a DID.

Keychains Index defines an extensible directory of a DID's keychains. It does not store the key material itself, but rather stores pointers to documents which do. By standardizing how various keychains are associated to a DID, the Keychains Index expands how a DID can be controlled and the possibilities of what it can do.

Keychains Index is a subdirectory in the [Identity Index (IDX) (CIP-11)](https://github.com/ceramicnetwork/CIP/issues/3) and is often linked from the [Root Index (CIP-12)](https://github.com/ceramicnetwork/CIP/issues/21).

## Motivation

**Extended Capabilities Provided by Multiple Keychains**: DIDs may need any number of keychains beyond just a basic seed to perform more specific functions related to various applications, platforms, encryption, or technology contexts. 

**DID Resilience and Improved Key Management**: By associating one or more keychains to the DID which can perform actions such as authentication, the Keychains Index provides the foundation for improving key management for DIDs. Instead of only authenticating via seed, DIDs can be authenticated by any number of keys in an auth keychain. This adds resilience and anti-fragility to a DID, since as long as the user maintains control of one of their authentication keys they will remain in control of their DID. These authentication keys are usually crypto wallet keys, so therefore key management is delegated to every wallet that holds a user's keys.

## Specification

The Keychains Index specification includes a doctype, schema, table, and tag.

![Keychains Index Diagram](https://uploads-ssl.webflow.com/5ebcbef3ac4954196dcdc7b5/5f1f08be4f7138c2b92b2e45_Keychains%20Index.jpg)

### Doctype

Keychains Index is a [Tile Doctype (CIP-8)](https://github.com/ceramicnetwork/CIP/issues/56).

### Schema

Keychains Index utilizes the [String Map (CIP-9)](https://github.com/ceramicnetwork/CIP/issues/50) schema, which simply stores a list of strings which map to other strings. In this context, the key string is used to name the keychain and the value string is used to store the location of the keychain. A reference to this schema should be included in your Keychains Index document when it is created.

### Table

The Keychains Index Table (coming soon) contains the standard set of properties that may be contained in any given Keychains Index. New properties can be added to the table by following the steps below. Additional properties not found in this table may be stored in any Keychains Index, however they may be less interoperable since others may not know what they represent. Here are some common examples of properties stored in the Keychains Index:

- `auth`: a link to an [Auth Keychain (CIP-20)](https://github.com/ceramicnetwork/CIP/issues/33), which contains authentication related data for a DID
- `legacy3box`: a link to a Legacy 3Box Keychain that is used to encrypt/decrypt data kept in 3Box data stores prior to (insert date of architecture migration)

**How to add a new property to the Keychains Index Table**

1. Choose a unique, descriptive property name.
2. Add a description for your property.
3. Submit a PR to the CIP repository updating the Keychains Index Table (coming soon) with your property.
4. Mention the authors of this CIP in the comments of your PR.

### Tags

When creating a Keychains Index document, add `KeychainsIndex` to the **tags** field.

## Example

An example Keychains Index document.

```json
"doctype": "tile"
"schema": "<insert canonical schema for String Map>"
"tags": ["KeychainsIndex", "StringMap"]
"content": {
  "auth": "ceramic://bafyljsdf1...",
  "legacy3box": "ceramic://bafysdfoijwe2..."
}
```

## Suggested Usage

**Root Index**: Keychains Index provides a directory of keychains, however keychains are just one type of resource that can be associated with a DID. The [Root Index (CIP-12)](https://github.com/ceramicnetwork/CIP/issues/21) provides a top-level root directory for resources, and can contain a property called `keychains` which stores a link to a Keychains Index. The recommended path from a DID to the Keychains Index is: `DID`/`Root Index`/`Keychains Index`.

## Rationale

**Extensibility & Flexibility:** It is impossible to predict all of the types of keychains that will need to be associated with any particular DID. Therefore Keychains Index was created to function an infinitely extensible directory that can support any number of keychains.

**Decentralization & Trust:** Keychain directory information is data that needs to be globally-available, censorship-resistant, and live permissionlessly in the public domain (not on any single server). Additionally this information should be owned by a DID and will need to be updated from time to time. These requirements make Ceramic the most appropriate platform for publishing this content.

## Implementation

**String Map Schema:** Find the String Map Schema [here](https://github.com/ceramicnetwork/CIP/issues/50).

**Keychains Index Table:** Find the table containing standard Keychains Index properties here (coming soon).

**Libraries:** Not yet available.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by michaelsena** [comment]
@oed should this be a String Map (CIP-9) or a DocId Map (CIP-10) schema? My thinking is String Map because there might be a scenario where a keychain is controlled by some external service or something? Thoughts?

**Comment by oed** [comment]
Stale, closing.
