### ISSUE TITLE
Data Interoperability Protocol (DIP)

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#18]
```
cip: 
title: Data Interoperability Protocol (DIP)
author: Michael Sena (@michaelsena), Joel Thorstensson (@oed)
discussions-to:
status: Idea
category: Standards
type: RFC
created: 2020-05-22
requires:
replaces: 
```

> 🚨 This is a placeholder for an idea, and we will work to draft the CIP at a later time. Feel free to leave comments and ideas on this issue.

## Simple Summary

**Data Interoperability Protocol (DIP)** is a standard framework for creating a DID-centric index of data collections that exist across all decentralized networks and centralized servers.

## Abstract

DIP is an extension of the [Identity Index Protocol (IIP) (CIP-11)](https://github.com/ceramicnetwork/CIP/issues/3) that describes how to add data to a [Collections Index (CIP-16)](https://github.com/ceramicnetwork/CIP/issues/26) in a way that makes it universally discoverable and interoperable across applications and platforms.

## Motivation

**Data interoperability**:

**Unified, DID-centric data routing**:

**Cross-platform support**:

## Specification

**Comment by oed** [comment]
Closing , stale.
