### ISSUE TITLE
Support ethr-did resolver

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#2]
```
cip: 
title: Support ethr-did resolver
author: Michael Sena (@michaelsena), Joel Thorstensson (@oed)
discussions-to:
status: Idea
category: Standards
type: Core
created: 2020-05-22
requires:
replaces: 
```

> 🚨 This is a placeholder for an idea, and we will work to draft the CIP at a later time. Feel free to leave comments and ideas on this issue.

## Simple Summary

This CIP proposes adding support for the ethr-did reslover to Ceramic. This would allow Ceramic documents to be created and managed with DIDs that conform to ethr-did method.

## Motivation

**Multi-DID support**: As Ceramic aims to be a DID-agnostic protocol, it should have the ability to resolve more DID signatures than just 3IDs. Ethr DID is a standard that some in the Ethereum community have used and it would be good to allow those DIDs to create and interact with documents in Ceramic.

**Comment by oed** [comment]
Closing, if desired this should be an issue on the js-ceramic repo.
