### ISSUE TITLE
Ceramic Javascript API

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/CIP#38]
```
cip: 4
title: Ceramic Javascript API
author: Joel Thorstensson (@oed), Janko Simonovic (@simonovic86)
discussions-to:
status: Last Call
category: Standards
type: Interface
created: 2020-06-05
```

## Simple Summary

This CIP describes the javascript api that is implemented by both `ceramic-core` and `ceramic-http-client`. It provides a common interface for interacting with the ceramic network.

## Abstract

This CIP provides a standard javascript interface for ceramic that allows developers to interact with a Ceramic instance. The interface includes abstractions that allow developers add their own doctypes, by implementing a simple interface. It also enables the DID provider to be passed to the Ceramic instance regardless if `ceramic-core` or `ceramic-http-client` is being used. This is enabled by having an `applyRecord` function that allows signed records to be passed from the http client to a remote node.

## Motivation

Having a standardized interface for using ceramic regardless if you're interacting with a remote node or not is crucial to the decentralization of the protocol. By creating a common api for both the core implementation and the http-client (plus potential future clients) will enable developers to easily swap between remote clients and more decentralized alternatives. 

## Specification

Below we define two main interfaces. `Doctype` which is an interface that each doctype in ceramic can extend in various ways, and `CeramicApi` which is the interface of Ceramic clients.

### `Doctype`

Below the `Doctype` interface is defined. Any new doctype has to expand this interface in order to expose the functionality of the particular doctype in a developer friendly way. The `DoctypeHandler` interface is also defined. It provides the function needed in order to verify the state transition function of a particular doctype.

```typescript
interface DocState {
  // DocState as defined in the implementation
}

interface Context {
    user?: User;
    ipfs?: Ipfs; // an ipfs instance
    resolver?: Resolver; // a DID resolver instance
    provider?: DIDProvider; // a DID provider (3ID provider initially)
    anchorService?: AnchorService;
    api?: CeramicApi; // the self reference to the Ceramic API
}

/**
 * Describes common doctype attributes
 */
abstract class Doctype extends EventEmitter {
    constructor(private _state: DocState, private _context: Context) {
        super()
    }

    get id(): string {
        return DoctypeUtils.createDocId(this.state.log[0])
    }

    get doctype(): string {
        return this._state.doctype
    }

    get content(): any {
        return cloneDeep(this.state.content)
    }

    get owners(): Array<string> {
        return cloneDeep(this.state.owners)
    }

    get state(): DocState {
        return cloneDeep(this._state)
    }

    set state(state: DocState) {
        this._state = state
    }

    get context(): Context {
        return this._context
    }

    get head(): CID {
        return this.state.log[this.state.log.length - 1]
    }

    /**
     * Makes a change on an existing document
     * @param params - Change parameters
     * @param opts - Initialisation options
     */
    abstract change(params: Record<string, any>, opts?: InitOpts): Promise<void>;
}

/**
 * Doctype decorator
 * @constructor
 */
function DoctypeStatic<T>() {
    return <U extends T>(constructor: U): any => { constructor };
}

/**
 * Doctype static signatures
 */
interface DoctypeConstructor {
    /**
     * Constructor signature
     * @param state - Doctype state
     */
    new (state: DocState): Doctype;

    /**
     * Makes genesis record
     * @param params - Create parameters
     * @param context - Ceramic context
     * @param opts - Initialization options
     */
    makeGenesis(params: Record<string, any>, context?: Context, opts?: InitOpts): Promise<Record<string, any>>;
}

interface DoctypeHandler<T extends Doctype> {
    /**
     * The string name of the doctype
     */
    name: string;

    /**
     * The doctype class
     */
    doctype: DoctypeConstructor;

    /**
     * Applies record to the document (genesis|signed|anchored)
     * @param record - Record intance
     * @param cid - Record CID
     * @param context - Ceramic context
     * @param state - Document state
     */
    applyRecord(record: any, cid: CID, context: Context, state?: DocState): Promise<DocState>;

}
```

### `CeramicApi` 

The `CeramicApi` is implemented by both `ceramic-core` and `ceramic-http-client` thus providing the same api for both remote clients and node instances.

```typescript
interface PinApi {
    add(docId: string): Promise<void>;
    rm(docId: string): Promise<void>;
    ls(docId?: string): Promise<AsyncIterable<string>>;
}

interface JsonRpc2Response {
    'id': string;
    'json-rpc': string;
    'result': object;
}

interface DIDProvider {
    send(jsonReq: object): JsonRpc2Response;
}

interface CeramicApi {
    pin: PinApi;
    ipfs: Ipfs.Ipfs;

    addDoctype<T extends Doctype>(doctypeHandler: DoctypeHandler<T>): void;
    createDocument<T extends Doctype>(doctype: string, params: object, opts?: InitOpts): Promise<T>;
    createDocumentFromGenesis<T extends Doctype>(genesis: any, opts?: InitOpts): Promise<T>;
    loadDocument<T extends Doctype>(docId: string, opts?: InitOpts): Promise<T>;
    applyRecord<T extends Doctype>(docId: string, record: object, opts?: InitOpts): Promise<T>;
    setDIDProvider (provider: DIDProvider): Promise<void>;
    close(): Promise<void>; // gracefully close the ceramic instance
}

```

## Rationale

Standardising the api of Ceramic clients allows developers to have the same expectations regardless of how they are interacting with Ceramic. The standardisation of the Doctype interface also makes it easier for developers to add their own doctypes without having to modify the ceramic code base.

## Implementation

Implementation will take place in [js-ceramic](https://github.com/ceramicnetwork/js-ceramic).

## Security Considerations

By allowing signing to happen client side in both `ceramic-core` and `ceramic-http-client` we can allow the users to always be in corntrol of their keys. When a user is interacting with the http client they can simply sign the data of the update record and the signed data can be passed over the http api to a cermic node in order to be applied to the document.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by simonovic86** [comment]
Should we define the `version` field or similar and expose it in the APIs interface? If we introduce some feature in the future which can possibly break the backward compatibility we should be able to detect API versions.

**Comment by oed** [comment]
@simonovic86 Hm, what version would be returned from this? The version of the api itself? My concern with this is that it might be confusing since the `ceramic-core` version will likely differ from the `ceramic-http-client` version.
Or would the version field simply say something like `ceramic-core@x.x.x` or `ceramic-http-client@x.x.x`?

**Comment by simonovic86** [comment]
@oed I thought about the API version therefore I think its `ceramic-http-client`.

I think it's ok for `ceramic-core` version to differ from the `ceramic-http-client` version. I guess that API versions will progress slower than the core. Does that make sense?

**Comment by oed** [comment]
I'm not sure. They might change either way. Isn't it enough that the packages have versions though? It would be weird if `ceramic-core` exposes the version of the http client right?

**Comment by simonovic86** [comment]
Makes sense. I think it's enough, too 👍

**Comment by michaelsena** [comment]
@simonovic86 would be good to circle back and rewrite this Draft after you've dug through the code :)

**Comment by simonovic86** [comment]
@michaelsena definitely! I'll write a detailed feedback after I run more tests :)

**Comment by simonovic86** [comment]
These are the changes based on the first _draft-0_ implementation of the proposed API. Let's reiterate more through it.

The `Doctype` interface should include the document ID since we are depending on it in the API. With that said, the minimal `Doctype` interface should look like this:

```javascript
interface Doctype {
    id: string;
    doctype: string;
    content: object;
    owners: Array<string>;
    state: DocState;
    head: CID;
}
```

There are situations where we need to sign the genesis record on document creation before applying it (TileHandler, etc.). We should leave that to the `Doctype` side and not to the `DoctypeHandler` since it is more natural for the _client_ to sign it and not the Ceramic instance. With that said the minimal `DoctypeHandler` interface should look something like this:

```javascript
interface DoctypeHandler<T extends Doctype> {
    name: string; // the string name of the doctype

    applyRecord(record: any, cid: CID, context: Context, state?: DocState): Promise<DocState>;
}
```

The Ceramic pinning API mimics the IPFS pinning API. We could change the `ls` return type to `Promise<AsyncIterable<string>>`. The interface could look like this:

```javascript
interface PinApi {
 
    add(docId: string): Promise<void>;

    rm(docId: string): Promise<void>;

    ls(docId?: string): Promise<AsyncIterable<string>>;
}
```

Since create/update/sign/etc. happens in the `Doctype` abstraction/layer these are the proposed changes to the `CeramicAPI` interface:

```javascript
interface CeramicApi {
    pin: PinApi;
    ipfs: Ipfs.Ipfs;

    addDoctype<T extends Doctype>(doctypeHandler: DoctypeHandler<T>): void;

    createFromGenesis<T extends Doctype>(record: any, opts?: InitOpts): Promise<T>;

    load<T extends Doctype>(docId: string, opts: InitOpts): Promise<T>;

    applyRecord<T extends Doctype>(docId: string, record: object): Promise<T>;

    close(): Promise<void>; // gracefully close the ceramic instance
}
```

The `createFromGenesis` enables us to have different layers of abstraction between `Doctype` and `DoctypeHandler`. 

`Doctype` implements functionality for manipulating the document and the `DoctypeHandler` _applies_ those changes.

We should also describe the `InitOpts` interface. Maybe that interface could be more flexible.

Let's discuss more about the APIs and naming as well! :)

**Comment by oed** [comment]
Thanks @simonovic86 that all makes sense.
About `CeramicApi`: I still think we need the `new` method (maybe called something else). If we don't have that there is no good way to construct new documents without having to create the genesis-record.

I assume `InitOpts` will likely change quite often adding new options so I didn't bother defining it.

**Comment by simonovic86** [comment]
Makes sense. Let's keep the `new` method in the Ceramic API.

I totally agree for the `InitOpts`. We will definitely change it a bunch of times. That said, we don't need to define it now :)

**Comment by oed** [comment]
Updated this according to our discussions and your implementation @simonovic86 👍

**Comment by simonovic86** [comment]
Updated this according to our discussions and to current implementation.

**Comment by oed** [comment]
Thanks @simonovic86! Looks great.
@michaelsena is the next step to just create a PR for this?

**Comment by michaelsena** [comment]
@simonovic86 @oed this is great! Quick question, if we wanted to separate out a commit function as discussed the other day, would we need a new CIP to define that, which would be submitted separately? If so, then let's create a PR -  this looks good to go.

**Comment by michaelsena** [comment]
We should also add the PR that contains the changes to this CIP in the implementations section.

**Comment by simonovic86** [comment]
> @simonovic86 @oed this is great! Quick question, if we wanted to separate out a commit function as discussed the other day, would we need a new CIP to define that, which would be submitted separately? If so, then let's create a PR - this looks good to go.

I think not. We can elaborate more about the topic but I think that we are covered with these APIs.

**Comment by oed** [comment]
Outdated, closing.
Please refer to the ceramic documentation: https://ceramicnetwork.github.io/js-ceramic/api/
