### ISSUE TITLE
String Map

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#50]
```
cip: 9
title: String Map
author: Michael Sena (@michaelsena), Joel Thorstensson (@oed)
status: Draft
category: Standards
type: RFC
created: 2020-07-13
requires: Tile Doctype (CIP-8)
```

## Simple Summary
The **String Map** defines a document that stores mappings from one string to another string.

## Abstract
For many use cases of Ceramic it is desirable to create a document that simply stores a list of mappings from a property to a value where both the property and value are strings.

## Motivation
Such a standard would be helpful in defining a basic schema that many in the Ceramic ecosystem can use when creating documents.

## Specification
The String Map specification consists of a doctype, a schema, and a tag.

### Doctype
The String Map schema is defined in a [tile doctype (CIP-N)](https://github.com/ceramicnetwork/CIP/issues/56).

### Schema
The String Map schema defines a document which maintains a list of strings that map to other strings. If this schema is used in a document, these rules will be enforced by the Ceramic protocol.

```jsx
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "StringMap",
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}
```

### Tags
When creating a document that conforms to the StringMap schema, add `StringMap` to the **tags** field.

## Rationale
This proposal is fairly straightforward and no other design considerations were made.

## Implementation
**String Map Schema**: This version of the String Map schema can be found at `ceramic://bafy.../?version` (will update after it is deployed).

## Usage
When creating a new document that conforms to the String Map schema, you should include the schema version included above in the `schema` property and the `StringMap` tag in the `tags` property.

## Security Considerations
None

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oed** [comment]
Closing, stale.
