### ISSUE TITLE
DocId Map

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#51]
```
cip: 10
title: DocId Map
author: Michael Sena (@michaelsena), Joel Thorstensson (@oed)
status: Draft
category: Standards
type: RFC
created: 2020-07-13
requires: Tile Doctype (CIP-8)
```

## Simple Summary
The **DocId Map** defines a document that stores mappings from strings to Ceramic DocIds.

## Abstract
For many use cases of Ceramic it is desirable to create a document that simply stores a list of mappings from a property to a value where the property is a string and the value is a Ceramic DocId.

## Motivation
Such a standard would be helpful in defining a basic schema that many in the Ceramic ecosystem can use when creating documents.

## Specification

The DocId Map specification consists of a doctype, a schema, and a tag.

### Doctype

The DocId Map is defined in a [Tile Doctype (CIP-8)](https://github.com/ceramicnetwork/CIP/issues/56).

### Schema

The DocId Map schema defines a document which maintains a list of properties that must be strings and values that must be Ceramic docIds. These rules will be enforced by the Ceramic protocol.

```jsx
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "DocIdMap",
  "additionalProperties": {
    "$ref": "#/definitions/CeramicDocId"
  },
  "definitions": {
    "CeramicDocId": {
      "type": "string",
      "pattern": "^ceramic://.+(\\?version=.+)?"
    }
  }
}
```

### Tags

When creating a document that conforms to the DocId Map schema, add `DocIdMap` to the `tags` field.

## Rationale
This proposal is fairly straightforward and no other design considerations were made.

## Implementation

**DocId Map Schema**: This version of the DocId Map schema can be found at `ceramic://bafy.../?version` (will update after it is deployed)

## Usage

When creating a new document that conforms to the DocId Map schema, you should include in the document header the schema version included above in the `schema` property and a `DocIdMap` tag in the `tags` property.

## Security Considerations
None

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by simonovic86** [comment]
@michaelsena @oed updated the schema

**Comment by oed** [comment]
@simonovic86 We should just force it to be a DocId of the form `ceramic://...`. The other format of docId is only needed when representing Ceramic documents in the http client.

**Comment by simonovic86** [comment]
@oed I'll remove the `v0` format. Also, we should think about refactoring the HTTP client API.

**Comment by oed** [comment]
Closing, stale
