### ISSUE TITLE
DID Array

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#53]
```
cip: 26
title: DID Array
author: Michael Sena (@michaelsena), Joel Thorstensson (@oed)
status: Draft
category: Standards
type: RFC
created: 21-07-2020
requires: Tile Doctype (CIP-8)
```

## Simple Summary
**DID Array** defines the format of a document that stores an array of DIDs.

## Abstract
For many use cases of Ceramic it is desirable to create a document that simply stores a list of DIDs. This could be useful for things like social graphs (follows), user lists, member lists, and more.

## Motivation
Such a standard would be helpful in defining a reusable schema that many in the Ceramic ecosystem can use when creating documents.

## Specification
The DID Array specification consists of a doctype, a schema, and a tag.

### Doctype
DID Array is stored in a [Tile Doctype (CIP-8)](https://github.com/ceramicnetwork/CIP/issues/56).

### Schema
The DID Array schema defines a document which maintains a list of DIDs. If this schema is used in a document, these rules will be enforced by the Ceramic protocol.

```jsx
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "title": "DIDArray",
  "items": {
    "$ref": "#/definitions/DID"
  },
  "definitions": {
    "DID": {
      "type": "string",
      "pattern": "^did:.+:.+"
    }
  }
}
```

### Tags
When creating a document that conforms to the DID Array schema, add `DIDArray` to the `tags` field.

## Rationale
This proposal is fairly straightforward and no other design considerations were made.

## Implementation
**DID Array Schema**: This version of the DID Array schema can be found at `ceramic://bafy.../?version` (TODO: update after deployment)

## Usage
When creating a new document that conforms to the DID Array schema, you should include the schema version included above in the `schema` property and the `DIDArray` tag in the `tags` property.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by simonovic86** [comment]
@oed @michaelsena updated the schema

**Comment by oed** [comment]
@simonovic86 we should only allow `did:*` not `DID:*`.

**Comment by simonovic86** [comment]
@oed tnx, updated 👍

**Comment by oed** [comment]
Great, ty :)

**Comment by oed** [comment]
Stale, closing.
