### ISSUE TITLE
DocId to DocId Map

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#54]
```
cip: 27
title: DocId to DocID Map
author: Michael Sena (@michaelsena), Joel Thorstensson (@oed)
status: Idea
category: Standards
type: RFC
created: 21-07-2020
requires: Tile Doctype (CIP-8)
```

## Simple Summary
**DocId to DocId Map** defines a schema that stores a list of mappings from DocId to DocId.

## Abstract
For many use cases of Ceramic it is desirable to create a document that simply stores a list of mappings from a DocId to another DocId.

## Motivation
Such a standard would be helpful in defining a basic schema that many in the Ceramic ecosystem can use when creating documents.

## Specification
The DocId to DocId Map specification consists of a doctype, a schema, and a tag.

### Doctype

The DocId to DocId Map is a [Tile Doctype (CIP-8)](https://github.com/ceramicnetwork/CIP/issues/56).

### Schema

The DocId to DocId Map schema defines a document which maintains a list of DocIds that map to other DocIds. If a document uses this schema, these rules will be enforced by the Ceramic protocol.

```jsx
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "DocIdDocIdMap",
  "propertyNames": {
    "pattern": "^ceramic://.+"
  },
  "additionalProperties": {
    "$ref": "#/definitions/CeramicDocId"
  },
  "definitions": {
    "CeramicDocId": {
      "type": "string",
      "pattern": "^ceramic://.+(\\?version=.+)?"
    }
  }
}
```

### Tags

When creating a document that conforms to the DocId to DocId Map schema, add `DocIdDocIdMap` to the `tags` field.

## Rationale
This proposal is fairly straightforward and no other design considerations were made.

## Implementation

**DocId to DocId Map Schema**: This version of the DocId to DocId Map schema can be found at `ceramic://bafy.../?version` (will update after it is deployed)

## Usage

When creating a new document that conforms to the DocId to DocId Map schema, you should include the schema version included above in the `schema` property and the `DocIdDocIdMap` tag in the `tags` property.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by michaelsena** [comment]
@oed need your input on schema here

**Comment by simonovic86** [comment]
@oed @michaelsena updated the schema

**Comment by oed** [comment]
Should we really allow version in the property name? This would allow one to add the same docId as property twice for different versions.

**Comment by simonovic86** [comment]
@oed I thought about not allowing that, too. I'll update the schema.

**Comment by oed** [comment]
Stale, closing.
