### ISSUE TITLE
3ID Doctype

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/CIP#6]
```
cip: 6
title: 3ID Doctype
author: Joel Thorstensson (@oed), Michael Sena (@michaelsena)
status: Draft
category: Standards
type: RFC
created: 2020-07-24
requires: Doctypes (CIP-5)
```

## Simple Summary

This CIP describes the `3id` doctype which is used to create DID documents. The [DID standard](https://w3c.github.io/did-core) provides a general format for verifiable decentralized digital  identities. Given a specific DID string, a DID document which contains  public keys, authentication authorization, etc. can be  resolved.

## Abstract

The `3id` doctype allows DIDs to be created which are controlled by a *management key* and that have a separate *signing key* as well as an *encryption key*. Each update to a 3ID document is signed by the *management key* and encoded using [dag-jose](https://github.com/ceramicnetwork/js-dag-jose). A separate [DID resolver](https://github.com/uport-project/did-resolver) can be implemented using ceramic to resolve a 3ID in the same way as any DID. This resolver converts the more compact content of the 3ID document into a standards compliant DID document.

## Motivation

The original motivation for the design of the Ceramic protocol was to enable the most decentralized DID method possible. It was only later realized that Ceramic can be used for any type of document in a more abstract way. The `3id` doctype therefore specifically defines a DID method based on Ceramic that fulfills the basic needs of a DID system. Since 3ID is native to Ceramic it works really nicely with the Ceramic protocol. A key feature of any DID method is the ability to revoke and rotate keys 3ID achieves this by relying on the security of the Ceramic conflict resolution system based on blockchain anchors.

## Specification

Below the record formats and state transitions of the `3id` doctype are specified. Together they should include all information needed to implement this doctype in Ceramic.

### Record formats

The **Genesis record** are stored in IPLD using the *dag-cbor* codec. It has the following required properties:

* `doctype` - MUST equal `3id`
* `data` - the initial JSON object of the document
* `owners` - a `secp256k1` key encoded using *multicodec* 

The JSON object of the document conform to the IPLD Schema defined below:

```ipldsch
type GenesisContent struct {
  publicKey {String:String}
}
```

Where each entry in the `publicKey` map has a key which is the name of the public key, and a value which is a multicodec encoded public key. It is reccomended that the following keys are added:

* `signing` - a `secp256k1` public key used for verifying signatures of the DID
* `encryption` - a `x25519` public key used to encrypt messages to the DID

**Signed records** of a `3id` document are encoded using [dag-jose](https://github.com/ceramicnetwork/js-dag-jose). Other than that they conform to the standard record format. The content of the `data` property should be a [json-patch](http://jsonpatch.com/) object which contains the difference from the previous document content state. The record should be signed by the *managementKey* (the key in the `owner` array) of the current document state.

### State transitions

Below the state transition logic for the three different supported records is described. 

#### Applying the Genesis Record

When the genesis record is applied a `DocState` object is created that looks like this:

```js
{
  doctype: '3id',
  metadata: {
    owners: genesisRecord.owners
  },
  content: genesisRecord.data,
  signature: SignatureStatus.GENESIS,
  anchorStatus: AnchorStatus.NOT_REQUESTED,
  log: [new CID(genesisRecord)]
}
```

In addition to this, the following should be verified:

* `owners` is an multicodec encoded `secp256k1` public key
* `content` should be a JSON object with the following requirements:
  * `publicKey` property contains a map with string keys and values which are DocIds
  * If present the `index` property should contain a docId as value

#### Applying a Signed Record

When a signed record is applied the `DocState` object should be modified in the following way:

```js
state.next = {
  content: applyJSONPatch(state.content, signedRecord.data),
  metadata: {
    owners: signedRecord.owners
  }
}
state.signature = SignatureStatus.SIGNED
state.anchorStatus = AnchorStatus.NOT_REQUESTED
state.log.push(new CID(signedRecord))
```

Where `applyJSONPatch` is a function that applies a json-patch and returns a new json object. In addition the following should be validated:

* If `owners` is defined it should be `secp256k1` public key that is different from `state.metadata.owners`.
* `content` should be a JSON object with the following requirements:
  * `publicKey` property contains a map with string keys and values which are DocIds
  * If present the `index` property should contain a docId as value
* The **dag-jose** signature should be valid and signed by the public key in the `owners` array in the `metadata` property (not the `next.metadata` property of the state)

#### Applying an Anchor Record

When an anchor record is applied the `DocState` object should be modified in the following way:

```js
state.anchorStatus = AnchorStatus.ANCHORED
state.anchorProof = anchorRecord.proof
state.content = state.next.content
state.metadata = Object.assign(state.metadata, state.next.metadata)
delete state.next
state.log.push(new CID(anchorRecord))
```

No additional validation needs to happen at this point in the state transition function.

## Rationale

The `3id` specification provides a simple way to implement a DID method on top of Ceramic. The content of the document is different from a regular DID document and instead it's converted to a standards complient DID document using the [3id-did-resolver](https://github.com/ceramicnetwork/js-ceramic/tree/develop/packages/3id-did-resolver) which makes the actual data stored and synced over the network much more minimal. The rules for what can go into the content of the document is left fairly minimal in order to allow for changes and iteration upon 3ID in the future.

## Implementation

A reference implementation of the `3id` doctype is provided in [js-ceramic](https://github.com/ceramicnetwork/js-ceramic). (see the `doctype-3id` package).

## Security Considerations

The 3ID doctype allows the `owners` array to change over time. This essentially allows users to do secure key rotation and revocation. Since the Ceramic protocol provides proof of publication of each document update and strict rules for how conflict resulution happens (earliest anchor wins), a user can be sure that their identity is safe even if old rotated keys gets compromised in the future.

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oed** [comment]
Closing this as the 3ID doctype is being consolidated with the Tile doctype.
