### ISSUE TITLE
Ceramic Doc reference

### ISSUE THREAD

**Issue by PaulLeCam** [ceramicnetwork/CIP#81]
```
cip: 81
title: Ceramic Doc reference
author: Paul Le Cam (@PaulLeCam)
status: Draft
category: Standards
type: RFC
created: 2021-02-15
edited: 2021-02-16
```
  

## Simple Summary

Provide a standard way to define a reference to a Ceramic document in a JSON schema.

## Abstract

This CIP defines a standard way to add a reference to an existing Ceramic document in a JSON schema, allowing for static discovery of such references.

## Motivation

It is sometimes necessary to reference Ceramic documents from other documents, such as a list containing the docIDs of individual Ceramic documents.
Currently, we are sometimes using definitions that can be referenced in a schema using `"$ref": "#/definitions/CeramicDocId"` for example, but this has not be defined as a standard.
Using local definitions to a schema also has the downside of providing no guaranty of being unique or having the definition matching any standard.

## Specification

References to Ceramic documents should use a `string` with the [`$id`](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.2) field of `ceramic://doc`, as defined by the following JSON schema:

```js
{
  type: 'string',
  $id: 'ceramic://doc',
  maxLength: 150,
}
```

## Rationale

Using the `$id` field on the object gives a unique namespace (`ceramic://`) and identifier (`doc`) so it creates a convention that can be used in similar CIPs.

Having this static way of identifying if a document references another document allows to simplify the associated logic, rather than relying on checking all string fields for the `ceramic://` prefix, or relying on `"$ref": "#/definitions/CeramicDocId"` matching the expected constraints.

## Backwards Compatibility

Ideally we should replace the use of the `CeramicDocId` definition by these objects in IDX schemas we provide.

## Implementation

None yet.

## Security Considerations

None I'm aware of.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oed** [comment]
Why does this need to be an object with an `id` property? Seems like it will make UX of the multiquery system worse by requiring the user to know if the path they are specifying includes a DocID or not, i.e. `/path/though/my/other/docs` vs `/path/id/though/my/id/other/id/docs`.

**Comment by PaulLeCam** [comment]
I mostly extracted this logic from https://github.com/ceramicnetwork/CIP/issues/82 with the idea there would more properties and only having the `id` property here is the exception rather than the rule.
I agree though that using `{ type: 'string', $id: 'ceramic://doc', maxLength: 150 }` directly would be simpler for such cases, shall we change the spec to this?

**Comment by oed** [comment]
I think that would makes sense yeah. Still need to dig through your other CIP!

**Comment by PaulLeCam** [comment]
@oed edited as suggested 👍

**Comment by PaulLeCam** [comment]
Folded into https://github.com/ceramicnetwork/CIP/issues/82
